export const runtime = "nodejs";
export const dynamic = "force-dynamic";
// apps/web/app/api/events/[id]/safety/route.ts
// The safety state machine for active events.
// CRITICAL: Reports with severity=CRITICAL auto-suspend the event.
// All actions are logged to SafetyLog for audit.

import { prisma } from "@/lib/db";
import {
  ok,
  created,
  badRequest,
  forbidden,
  notFound,
  validationError,
  requireUser,
  logAudit,
  withErrorHandler,
} from "@/lib/api";
import { rateLimit, strictLimiter } from "@/lib/rate-limit";
import {
  SafetyEscalationSchema,
  CheckInSchema,
  CreateReportSchema,
} from "@/lib/validators";
import { notifyAdmins } from "@/lib/notifications";
import type { NextRequest } from "next/server";

type RouteCtx = { params: { id: string } };

// ---- POST /api/events/[id]/safety/checkin — guest checks in with safety code ----

export async function POST(req: NextRequest, { params }: RouteCtx) {
  const { user, response } = await requireUser(req);
  if (!user) return response!;

  const body = await req.json();
  const action = (body.action as string) ?? "";

  if (action === "checkin") {
    return handleCheckIn(req, params.id, user.id, body);
  }

  if (action === "escalate") {
    return handleEscalation(req, params.id, user, body);
  }

  if (action === "start") {
    return handleEventStart(req, params.id, user);
  }

  if (action === "end") {
    return handleEventEnd(req, params.id, user);
  }

  return badRequest("Unknown action. Valid: checkin, escalate, start, end");
}

// ---- Check-in: guest provides safety code generated by host at event start ----
async function handleCheckIn(
  req: NextRequest,
  eventId: string,
  userId: string,
  body: unknown
) {
  const parseResult = CheckInSchema.safeParse(body);
  if (!parseResult.success) return validationError(parseResult.error);

  const event = await prisma.event.findUnique({ where: { id: eventId } });
  if (!event) return notFound("Event");

  if (event.status !== "ACTIVE") {
    return badRequest("Event is not currently active");
  }

  // Verify safety code against bcrypt hash
  if (!event.safetyCode || !(await verifySafetyCode(parseResult.data.safetyCode, event.safetyCode))) {
    return forbidden("Invalid safety code");
  }

  const rsvp = await prisma.rSVP.findUnique({
    where: { eventId_userId: { eventId, userId } },
  });

  if (!rsvp || rsvp.status !== "CONFIRMED") {
    return forbidden("You don't have a confirmed RSVP for this event");
  }

  await prisma.rSVP.update({
    where: { eventId_userId: { eventId, userId } },
    data: { checkedIn: true, checkedInAt: new Date() },
  });

  await prisma.safetyLog.create({
    data: {
      eventId,
      actorId: userId,
      type: "GUEST_CHECKED_IN",
      payload: { userId },
    },
  });

  return ok({ message: "Checked in successfully. Enjoy the gathering!" });
}

// ---- Escalation: report a safety issue during an active event ----
// CRITICAL severity → immediate event suspension + admin notification
async function handleEscalation(
  req: NextRequest,
  eventId: string,
  user: { id: string; role: string },
  body: unknown
) {
  // Strict rate limit: 3 escalations per 15 min per user
  const limited = await rateLimit(req, strictLimiter, `escalate:${user.id}`);
  if (limited) return limited;

  const parseResult = SafetyEscalationSchema.safeParse({ eventId, ...body });
  if (!parseResult.success) return validationError(parseResult.error);

  const { severity, description } = parseResult.data;

  const event = await prisma.event.findUnique({ where: { id: eventId } });
  if (!event) return notFound("Event");

  // Auto-suspend on CRITICAL
  if (severity === "CRITICAL") {
    await prisma.event.update({
      where: { id: eventId },
      data: {
        status: "SUSPENDED",
        suspendedAt: new Date(),
        suspendReason: `Auto-suspended: CRITICAL safety report from user ${user.id}`,
      },
    });

    // Notify all admins within <10 min SLA
    await notifyAdmins({
      type: "CRITICAL_SAFETY_ESCALATION",
      eventId,
      reporterId: user.id,
      description,
    });
  }

  // Create the formal report
  const report = await prisma.report.create({
    data: {
      filerId: user.id,
      eventId,
      type: "SAFETY_CONCERN",
      severity,
      description,
      status: severity === "CRITICAL" ? "INVESTIGATING" : "OPEN",
    },
  });

  await prisma.safetyLog.create({
    data: {
      eventId,
      actorId: user.id,
      type: severity === "CRITICAL" ? "ESCALATED" : "REPORT_FILED",
      payload: { reportId: report.id, severity, description },
    },
  });

  await logAudit({
    userId: user.id,
    action: "safety.escalation",
    entity: "Event",
    entityId: eventId,
    metadata: { severity, reportId: report.id },
    req,
  });

  return created({
    report,
    message:
      severity === "CRITICAL"
        ? "Event suspended. Our safety team has been notified and will respond within 10 minutes."
        : "Report filed. Our team will review within 12 hours.",
  });
}

// ---- Host starts the event — generates safety code, sets status ACTIVE ----
async function handleEventStart(
  req: NextRequest,
  eventId: string,
  user: { id: string; role: string }
) {
  const event = await prisma.event.findUnique({ where: { id: eventId } });
  if (!event) return notFound("Event");

  if (event.hostId !== user.id && user.role !== "ADMIN") {
    return forbidden("Only the host can start the event");
  }

  if (event.status !== "PUBLISHED") {
    return badRequest(`Cannot start an event with status: ${event.status}`);
  }

  // Generate 6-character alphanumeric safety code
  const safetyCode = generateSafetyCode();
  const safetyCodeHash = await hashSafetyCode(safetyCode);

  await prisma.event.update({
    where: { id: eventId },
    data: { status: "ACTIVE", safetyCode: safetyCodeHash },
  });

  await prisma.safetyLog.create({
    data: {
      eventId,
      actorId: user.id,
      type: "EVENT_STARTED",
      payload: { startedAt: new Date() },
    },
  });

  // Return the safety code to the host — they share it verbally with guests
  return ok({ safetyCode, message: "Event started. Share the safety code with your guests at arrival." });
}

// ---- Host ends the event ----
async function handleEventEnd(
  req: NextRequest,
  eventId: string,
  user: { id: string; role: string }
) {
  const event = await prisma.event.findUnique({ where: { id: eventId } });
  if (!event) return notFound("Event");

  if (event.hostId !== user.id && user.role !== "ADMIN") {
    return forbidden("Only the host can end the event");
  }

  if (event.status !== "ACTIVE") {
    return badRequest("Event is not currently active");
  }

  await prisma.event.update({
    where: { id: eventId },
    data: {
      status: "COMPLETED",
      safetyCode: null, // invalidate code
    },
  });

  await prisma.safetyLog.create({
    data: {
      eventId,
      actorId: user.id,
      type: "EVENT_ENDED",
      payload: { endedAt: new Date() },
    },
  });

  return ok({ message: "Event ended. Guests will be prompted to leave reviews." });
}

// ---- Helpers ----

function generateSafetyCode(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no 0/O/I/1 to avoid confusion
  // crypto.getRandomValues() uses the OS CSPRNG — never Math.random() for security codes
  const bytes = new Uint8Array(6);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => chars[b % chars.length]).join("");
}

async function hashSafetyCode(code: string): Promise<string> {
  const { hash } = await import("bcryptjs");
  return hash(code, 10);
}

async function verifySafetyCode(code: string, hashed: string): Promise<boolean> {
  const { compare } = await import("bcryptjs");
  return compare(code, hashed);
}
